### ISSUE TITLE
Installation via composer

### ISSUE THREAD

**Issue by PELock** [profburial/tordetect#2]
I've added your package via composer to my Yii2 project (like any other packages).

And it throws "Class 'ProfBurial\TorDetect\Client' not found"

Did you even try to install it via composer anywhere?

**Comment by profburial** [comment]
@PELock I did, and it should work. Try `composer dump-autoload -o`.

**Comment by PELock** [comment]
God damned composer, I hate this thing, sometimes it works, sometime it doesn't, constant self-update ;)

Is there any reason except composer for this to happen? Also why did you split like 10 functions into 2 classes?

**Comment by profburial** [comment]
@PELock

> Is there any reason except composer for this to happen?

Nope. Everything is loaded via psr-4, so if you have any issues, it's composer related.

>  Also why did you split like 10 functions into 2 classes?

Separation of concerns. Methods for retrieving data from the data source shouldn't be needed by the client.

**Comment by PELock** [comment]
"officiousness is worse than fascism" ;)
