### ISSUE TITLE
This "library" is useless!

### ISSUE THREAD

**Issue by PELock** [profburial/tordetect#3]
I thought it would download latest TOR exit nodes, but this library doesn't do anything except for checking if the provided IP is on the list and if the list file was updated.

This is bloat code!
1. It doesn't load the current TOR node exits
2. It doesn't contain current TOR node exits list (.json file)
3. If you try to load the class you get the exception (.json file not found)
4. You have to download CSV file yourself, convert it to .json and pass it to this class, and it will basically do in_array() on the IP list

I wasted so much time on something so useless...

**Comment by profburial** [comment]
@PELock If you want to share your code, I'll be glad to help. It sounds to me like you didn't create a json file to store the exit nodes in, which is why you are getting that exception. 

This library was created for a personal project, and it continues to work well. Please see the disclaimer in the readme file. 

> You probably shouldn't use this lib as is if you are wanting to do anything serious.

You're more than welcome to submit a PR to keep this library from being "bloat code".

**Comment by PELock** [comment]
How is this a library anyway?
- It doesn't do what it says (try to install it and use it out of box).
- It doesn't fetch the TOR exit nodes from the Internet.
- It doesn't convert available lists from CSV into JSON format.
- Everything has to be done manually.
- The only thing it does is checking if the provided IP is in the array.

This entire so called "library" can be replaced with one in_array() function call when you already fetch the CSV list yourself. And you made 2 classes out of 10 or something functions, 1 extra class for exceptions. And still it's useless code. Why did you even publish it, to bump up your GitHub repositories list in your CV?

How do you call a "library" like that?

You can replace your entire "library" with this (if you need to fetch the list yourself and convert it yourself anyway):

```
function IsTOR($ip)
{
  $exitNodes = [ "ip1", "ip2" ...];

  return in_array( $ip, $exitNodes );
}
```

**Comment by profburial** [comment]
@PELock I appreciate your feedback. It gives me a lot of insight into how users of your mindset will view/use this package.  

Like I said, I think that your main problem with using this package was not creating your json file to store exit nodes. If you were to do that, it would work as expected. Again, you're more than welcome to share your code so I can try to help you get it working. 

There really isn't any need for this vitriol. If you don't like the code, fork it and contribute something positive, or simply write your own.
